pipeline:
  build-apps:
    image: node:12
    commands:
      - yarn build
  publish:
    image: plugins/ecr
    when:
      event: tag
    region: us-east-1
    repo: 558830342743.dkr.ecr.us-east-1.amazonaws.com/cs-drone-poc
    build_args: "VERSION=${DRONE_TAG##v}"
    tag:
      - ${DRONE_TAG##v}
  mark-as-latest-if-stable:
    image: plugins/webhook
    when:
      event: tag
    urls: http://releases.ingress.vtex.io/latest-if-stable/cs-drone-poc/${DRONE_TAG##v}
    method: PATCH
  notify:
    image: plugins/slack
    template: "*{{Build.Status}}*: <{{Build.Link}}|{{Repo.Owner}}/{{Repo.Name}}> (${DRONE_TAG##v}) by {{Build.Author}}"
    webhook: https://hooks.slack.com/services/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
    when:
      event: tag
      status: [success, failure]